apiVersion: v1
kind: ConfigMap
metadata:
  name: artillery-config
data:
  test.yaml: |
    config:
      target: "http://php-apache"
      phases:
        - duration: 300
          arrivalRate: 200
    scenarios:
      - flow:
          - get:
              url: "/"
